// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest       = require("bs-jest/src/jest.js");
var RereactDom = require("../rereactDom.bs.js");

describe("List", (function () {
        Jest.test("first smaller than second one", (function () {
                var input = RereactDom.equalizeList(/* :: */[
                      1,
                      /* [] */0
                    ], /* :: */[
                      1,
                      /* :: */[
                        6,
                        /* [] */0
                      ]
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            /* :: */[
                              /* Some */[1],
                              /* :: */[
                                /* None */0,
                                /* [] */0
                              ]
                            ],
                            /* :: */[
                              /* Some */[1],
                              /* :: */[
                                /* Some */[6],
                                /* [] */0
                              ]
                            ]
                          ], Jest.Expect[/* expect */0](input));
              }));
        Jest.test("sameSize", (function () {
                var input = RereactDom.equalizeList(/* :: */[
                      1,
                      /* :: */[
                        24,
                        /* [] */0
                      ]
                    ], /* :: */[
                      214,
                      /* :: */[
                        123,
                        /* [] */0
                      ]
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            /* :: */[
                              /* Some */[1],
                              /* :: */[
                                /* Some */[24],
                                /* [] */0
                              ]
                            ],
                            /* :: */[
                              /* Some */[214],
                              /* :: */[
                                /* Some */[123],
                                /* [] */0
                              ]
                            ]
                          ], Jest.Expect[/* expect */0](input));
              }));
        Jest.test("second one smaller than first one", (function () {
                var input = RereactDom.equalizeList(/* :: */[
                      1,
                      /* :: */[
                        24,
                        /* [] */0
                      ]
                    ], /* :: */[
                      214,
                      /* [] */0
                    ]);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            /* :: */[
                              /* Some */[1],
                              /* :: */[
                                /* Some */[24],
                                /* [] */0
                              ]
                            ],
                            /* :: */[
                              /* Some */[214],
                              /* :: */[
                                /* None */0,
                                /* [] */0
                              ]
                            ]
                          ], Jest.Expect[/* expect */0](input));
              }));
        Jest.test("both empty", (function () {
                var input = RereactDom.equalizeList(/* [] */0, /* [] */0);
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            /* [] */0,
                            /* [] */0
                          ], Jest.Expect[/* expect */0](input));
              }));
        return Jest.test("both empty", (function () {
                      var input = RereactDom.equalizeList(/* :: */[
                            1,
                            /* :: */[
                              2,
                              /* :: */[
                                3,
                                /* :: */[
                                  4,
                                  /* [] */0
                                ]
                              ]
                            ]
                          ], /* :: */[
                            1,
                            /* :: */[
                              2,
                              /* [] */0
                            ]
                          ]);
                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                  /* :: */[
                                    /* Some */[1],
                                    /* :: */[
                                      /* Some */[2],
                                      /* :: */[
                                        /* Some */[3],
                                        /* :: */[
                                          /* Some */[4],
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ],
                                  /* :: */[
                                    /* Some */[1],
                                    /* :: */[
                                      /* Some */[2],
                                      /* :: */[
                                        /* None */0,
                                        /* :: */[
                                          /* None */0,
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ], Jest.Expect[/* expect */0](input));
                    }));
      }));

/*  Not a pure module */
