// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var defaultProps = /* record */[
  /* id : None */0,
  /* value : None */0,
  /* className : None */0,
  /* onClick : None */0,
  /* onChange : None */0
];

exports.defaultProps = defaultProps;
/* No side effect */
