// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Didact = require("./didact.bs.js");

function div(param, param$1) {
  return Didact.createDomElement("div", param, param$1);
}

function h1(param, param$1) {
  return Didact.createDomElement("h1", param, param$1);
}

function h2(param, param$1) {
  return Didact.createDomElement("h2", param, param$1);
}

function h3(param, param$1) {
  return Didact.createDomElement("h3", param, param$1);
}

function h4(param, param$1) {
  return Didact.createDomElement("h4", param, param$1);
}

function h5(param, param$1) {
  return Didact.createDomElement("h5", param, param$1);
}

function h6(param, param$1) {
  return Didact.createDomElement("h6", param, param$1);
}

function span(param, param$1) {
  return Didact.createDomElement("span", param, param$1);
}

function ul(param, param$1) {
  return Didact.createDomElement("ul", param, param$1);
}

function li(param, param$1) {
  return Didact.createDomElement("li", param, param$1);
}

function img(param, param$1) {
  return Didact.createDomElement("img", param, param$1);
}

function button(param, param$1) {
  return Didact.createDomElement("button", param, param$1);
}

function input(param, param$1) {
  return Didact.createDomElement("input", param, param$1);
}

exports.div    = div;
exports.h1     = h1;
exports.h2     = h2;
exports.h3     = h3;
exports.h4     = h4;
exports.h5     = h5;
exports.h6     = h6;
exports.span   = span;
exports.ul     = ul;
exports.li     = li;
exports.img    = img;
exports.button = button;
exports.input  = input;
/* No side effect */
