// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Didact         = require("./didact.bs.js");
var DidactElements = require("./didactElements.bs.js");

var match = document.getElementById("container");

if (match !== null) {
  console.log(match);
  var componentA = DidactElements.h1(/* :: */[
        Didact.stringToElement("Hola"),
        /* [] */0
      ], /* () */0);
  var componentB = DidactElements.div(/* :: */[
        DidactElements.button(/* :: */[
              Didact.stringToElement("click me"),
              /* [] */0
            ], /* () */0),
        /* [] */0
      ], /* () */0);
  Didact.render(componentA, match);
  setInterval((function () {
          Didact.render(componentB, match);
          return /* () */0;
        }), 2000);
} else {
  console.log("No dom element found :(");
}

/* match Not a pure module */
