// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List  = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function createDomElement(name, id, value, onClick, onChange, children, _) {
  return /* Nested */Block.__(1, [
            name,
            /* record */[
              /* id */id,
              /* value */value,
              /* onClick */onClick,
              /* onChange */onChange
            ],
            children
          ]);
}

function div(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("div", param, param$1, param$2, param$3, param$4, param$5);
}

function h1(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("h1", param, param$1, param$2, param$3, param$4, param$5);
}

function h2(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("h2", param, param$1, param$2, param$3, param$4, param$5);
}

function h3(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("h3", param, param$1, param$2, param$3, param$4, param$5);
}

function h4(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("h4", param, param$1, param$2, param$3, param$4, param$5);
}

function h5(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("h5", param, param$1, param$2, param$3, param$4, param$5);
}

function h6(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("h6", param, param$1, param$2, param$3, param$4, param$5);
}

function span(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("span", param, param$1, param$2, param$3, param$4, param$5);
}

function ul(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("ul", param, param$1, param$2, param$3, param$4, param$5);
}

function li(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("li", param, param$1, param$2, param$3, param$4, param$5);
}

function img(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("img", param, param$1, param$2, param$3, param$4, param$5);
}

function button(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("button", param, param$1, param$2, param$3, param$4, param$5);
}

function input(param, param$1, param$2, param$3, param$4, param$5) {
  return createDomElement("input", param, param$1, param$2, param$3, param$4, param$5);
}

function addProps(domElement, props) {
  var match = props[/* id */0];
  if (match) {
    domElement.setAttribute("id", match[0]);
  }
  var match$1 = props[/* value */1];
  if (match$1) {
    domElement.setAttribute("value", match$1[0]);
  }
  var match$2 = props[/* onClick */2];
  if (match$2) {
    domElement.addEventListener("click", match$2[0]);
  }
  var match$3 = props[/* onChange */3];
  if (match$3) {
    domElement.addEventListener("change", match$3[0]);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

function mapReactElement(parentElement, reactElement) {
  if (reactElement.tag) {
    var elements = reactElement[2];
    var name = reactElement[0];
    if (name === "List") {
      return /* INested */Block.__(1, [
                name,
                List.map((function (param) {
                        return mapReactElement(parentElement, param);
                      }), elements)
              ]);
    } else {
      var node = document.createElement(name);
      parentElement.appendChild(node);
      addProps(node, reactElement[1]);
      return /* INested */Block.__(1, [
                name,
                List.map((function (param) {
                        return mapReactElement(node, param);
                      }), elements)
              ]);
    }
  } else {
    return /* IFlat */Block.__(0, [List.map((function (param) {
                      return reconcile(parentElement, param);
                    }), reactElement[0])]);
  }
}

function reconcile(parentElement, element) {
  if (element.tag) {
    var component = element[0];
    var subElements = Curry._1(component[/* render */1], /* () */0);
    var instanceSubTree = mapReactElement(parentElement, subElements);
    return /* record */[
            /* component : Some */[component],
            /* element */element,
            /* instanceSubTree */instanceSubTree,
            /* domElement */parentElement,
            /* subElements */subElements
          ];
  } else {
    parentElement.innerText = element[0];
    return /* record */[
            /* component : None */0,
            /* element */element,
            /* instanceSubTree : IFlat */Block.__(0, [/* [] */0]),
            /* domElement */parentElement,
            /* subElements : Flat */Block.__(0, [/* [] */0])
          ];
  }
}

var renderReactElement = mapReactElement;

function render(reactElement, parentElement) {
  var match = parentElement.lastElementChild;
  if (match !== null) {
    parentElement.removeChild(match);
    return mapReactElement(parentElement, reactElement);
  } else {
    console.log("No child");
    return mapReactElement(parentElement, reactElement);
  }
}

exports.createDomElement   = createDomElement;
exports.div                = div;
exports.h1                 = h1;
exports.h2                 = h2;
exports.h3                 = h3;
exports.h4                 = h4;
exports.h5                 = h5;
exports.h6                 = h6;
exports.span               = span;
exports.ul                 = ul;
exports.li                 = li;
exports.img                = img;
exports.button             = button;
exports.input              = input;
exports.addProps           = addProps;
exports.mapReactElement    = mapReactElement;
exports.reconcile          = reconcile;
exports.renderReactElement = renderReactElement;
exports.render             = render;
/* No side effect */
